// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_OLY_xh3u26_g8hKQwVEAXDrGS08tSY',
    appId: '1:209889654525:web:c272fb8f8ea1a9046f7094',
    messagingSenderId: '209889654525',
    projectId: 'rgpet-961cd',
    authDomain: 'rgpet-961cd.firebaseapp.com',
    storageBucket: 'rgpet-961cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdC9vcE1oVkNAryeG6_Qh2CM3rYWK1zMg',
    appId: '1:209889654525:android:5f37f280bf44e4ea6f7094',
    messagingSenderId: '209889654525',
    projectId: 'rgpet-961cd',
    storageBucket: 'rgpet-961cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLJBjkp9p_0S40QVLDNrskaVAEuh7UGc',
    appId: '1:209889654525:ios:e1212d8436eaf68b6f7094',
    messagingSenderId: '209889654525',
    projectId: 'rgpet-961cd',
    storageBucket: 'rgpet-961cd.firebasestorage.app',
    iosBundleId: 'com.example.rgpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLJBjkp9p_0S40QVLDNrskaVAEuh7UGc',
    appId: '1:209889654525:ios:e1212d8436eaf68b6f7094',
    messagingSenderId: '209889654525',
    projectId: 'rgpet-961cd',
    storageBucket: 'rgpet-961cd.firebasestorage.app',
    iosBundleId: 'com.example.rgpet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA_OLY_xh3u26_g8hKQwVEAXDrGS08tSY',
    appId: '1:209889654525:web:457e2a319eaa2fe06f7094',
    messagingSenderId: '209889654525',
    projectId: 'rgpet-961cd',
    authDomain: 'rgpet-961cd.firebaseapp.com',
    storageBucket: 'rgpet-961cd.firebasestorage.app',
  );
}
